# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AlbumDownloadCreatedParameters`.
# Please instead update this file by running `bin/tapioca dsl AlbumDownloadCreatedParameters`.


class AlbumDownloadCreatedParameters
  sig { returns(T.nilable(::String)) }
  def album_id; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def album_id=(value); end
end
