# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AlbumSerializer`.
# Please instead update this file by running `bin/tapioca dsl AlbumSerializer`.


class AlbumSerializer
  sig { returns(Album) }
  def album; end
end
