# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ICloudPhotoDownloadSerializer`.
# Please instead update this file by running `bin/tapioca dsl ICloudPhotoDownloadSerializer`.


class ICloudPhotoDownloadSerializer
  sig { returns(ICloudPhotoDownload) }
  def download; end
end
