# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PhotoSerializer`.
# Please instead update this file by running `bin/tapioca dsl PhotoSerializer`.


class PhotoSerializer
  sig { returns(Photo) }
  def photo; end
end
